// Code generated by ent, DO NOT EDIT.

package ent

import (
	"TerminSystem/ent/appointment"
	"TerminSystem/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AppointmentUpdate is the builder for updating Appointment entities.
type AppointmentUpdate struct {
	config
	hooks    []Hook
	mutation *AppointmentMutation
}

// Where appends a list predicates to the AppointmentUpdate builder.
func (au *AppointmentUpdate) Where(ps ...predicate.Appointment) *AppointmentUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetName sets the "name" field.
func (au *AppointmentUpdate) SetName(s string) *AppointmentUpdate {
	au.mutation.SetName(s)
	return au
}

// SetNillableName sets the "name" field if the given value is not nil.
func (au *AppointmentUpdate) SetNillableName(s *string) *AppointmentUpdate {
	if s != nil {
		au.SetName(*s)
	}
	return au
}

// SetEmail sets the "email" field.
func (au *AppointmentUpdate) SetEmail(s string) *AppointmentUpdate {
	au.mutation.SetEmail(s)
	return au
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (au *AppointmentUpdate) SetNillableEmail(s *string) *AppointmentUpdate {
	if s != nil {
		au.SetEmail(*s)
	}
	return au
}

// SetPhone sets the "phone" field.
func (au *AppointmentUpdate) SetPhone(s string) *AppointmentUpdate {
	au.mutation.SetPhone(s)
	return au
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (au *AppointmentUpdate) SetNillablePhone(s *string) *AppointmentUpdate {
	if s != nil {
		au.SetPhone(*s)
	}
	return au
}

// SetType sets the "type" field.
func (au *AppointmentUpdate) SetType(a appointment.Type) *AppointmentUpdate {
	au.mutation.SetType(a)
	return au
}

// SetNillableType sets the "type" field if the given value is not nil.
func (au *AppointmentUpdate) SetNillableType(a *appointment.Type) *AppointmentUpdate {
	if a != nil {
		au.SetType(*a)
	}
	return au
}

// SetDelkey sets the "delkey" field.
func (au *AppointmentUpdate) SetDelkey(s string) *AppointmentUpdate {
	au.mutation.SetDelkey(s)
	return au
}

// SetNillableDelkey sets the "delkey" field if the given value is not nil.
func (au *AppointmentUpdate) SetNillableDelkey(s *string) *AppointmentUpdate {
	if s != nil {
		au.SetDelkey(*s)
	}
	return au
}

// SetStartTime sets the "start_time" field.
func (au *AppointmentUpdate) SetStartTime(t time.Time) *AppointmentUpdate {
	au.mutation.SetStartTime(t)
	return au
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (au *AppointmentUpdate) SetNillableStartTime(t *time.Time) *AppointmentUpdate {
	if t != nil {
		au.SetStartTime(*t)
	}
	return au
}

// SetEndTime sets the "end_time" field.
func (au *AppointmentUpdate) SetEndTime(t time.Time) *AppointmentUpdate {
	au.mutation.SetEndTime(t)
	return au
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (au *AppointmentUpdate) SetNillableEndTime(t *time.Time) *AppointmentUpdate {
	if t != nil {
		au.SetEndTime(*t)
	}
	return au
}

// SetDescription sets the "description" field.
func (au *AppointmentUpdate) SetDescription(s string) *AppointmentUpdate {
	au.mutation.SetDescription(s)
	return au
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (au *AppointmentUpdate) SetNillableDescription(s *string) *AppointmentUpdate {
	if s != nil {
		au.SetDescription(*s)
	}
	return au
}

// Mutation returns the AppointmentMutation object of the builder.
func (au *AppointmentUpdate) Mutation() *AppointmentMutation {
	return au.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *AppointmentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, au.sqlSave, au.mutation, au.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (au *AppointmentUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AppointmentUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AppointmentUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (au *AppointmentUpdate) check() error {
	if v, ok := au.mutation.Name(); ok {
		if err := appointment.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Appointment.name": %w`, err)}
		}
	}
	if v, ok := au.mutation.Email(); ok {
		if err := appointment.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Appointment.email": %w`, err)}
		}
	}
	if v, ok := au.mutation.Phone(); ok {
		if err := appointment.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "Appointment.phone": %w`, err)}
		}
	}
	if v, ok := au.mutation.GetType(); ok {
		if err := appointment.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Appointment.type": %w`, err)}
		}
	}
	if v, ok := au.mutation.Delkey(); ok {
		if err := appointment.DelkeyValidator(v); err != nil {
			return &ValidationError{Name: "delkey", err: fmt.Errorf(`ent: validator failed for field "Appointment.delkey": %w`, err)}
		}
	}
	return nil
}

func (au *AppointmentUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := au.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(appointment.Table, appointment.Columns, sqlgraph.NewFieldSpec(appointment.FieldID, field.TypeInt))
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.Name(); ok {
		_spec.SetField(appointment.FieldName, field.TypeString, value)
	}
	if value, ok := au.mutation.Email(); ok {
		_spec.SetField(appointment.FieldEmail, field.TypeString, value)
	}
	if value, ok := au.mutation.Phone(); ok {
		_spec.SetField(appointment.FieldPhone, field.TypeString, value)
	}
	if value, ok := au.mutation.GetType(); ok {
		_spec.SetField(appointment.FieldType, field.TypeEnum, value)
	}
	if value, ok := au.mutation.Delkey(); ok {
		_spec.SetField(appointment.FieldDelkey, field.TypeString, value)
	}
	if value, ok := au.mutation.StartTime(); ok {
		_spec.SetField(appointment.FieldStartTime, field.TypeTime, value)
	}
	if value, ok := au.mutation.EndTime(); ok {
		_spec.SetField(appointment.FieldEndTime, field.TypeTime, value)
	}
	if value, ok := au.mutation.Description(); ok {
		_spec.SetField(appointment.FieldDescription, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{appointment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	au.mutation.done = true
	return n, nil
}

// AppointmentUpdateOne is the builder for updating a single Appointment entity.
type AppointmentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AppointmentMutation
}

// SetName sets the "name" field.
func (auo *AppointmentUpdateOne) SetName(s string) *AppointmentUpdateOne {
	auo.mutation.SetName(s)
	return auo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (auo *AppointmentUpdateOne) SetNillableName(s *string) *AppointmentUpdateOne {
	if s != nil {
		auo.SetName(*s)
	}
	return auo
}

// SetEmail sets the "email" field.
func (auo *AppointmentUpdateOne) SetEmail(s string) *AppointmentUpdateOne {
	auo.mutation.SetEmail(s)
	return auo
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (auo *AppointmentUpdateOne) SetNillableEmail(s *string) *AppointmentUpdateOne {
	if s != nil {
		auo.SetEmail(*s)
	}
	return auo
}

// SetPhone sets the "phone" field.
func (auo *AppointmentUpdateOne) SetPhone(s string) *AppointmentUpdateOne {
	auo.mutation.SetPhone(s)
	return auo
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (auo *AppointmentUpdateOne) SetNillablePhone(s *string) *AppointmentUpdateOne {
	if s != nil {
		auo.SetPhone(*s)
	}
	return auo
}

// SetType sets the "type" field.
func (auo *AppointmentUpdateOne) SetType(a appointment.Type) *AppointmentUpdateOne {
	auo.mutation.SetType(a)
	return auo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (auo *AppointmentUpdateOne) SetNillableType(a *appointment.Type) *AppointmentUpdateOne {
	if a != nil {
		auo.SetType(*a)
	}
	return auo
}

// SetDelkey sets the "delkey" field.
func (auo *AppointmentUpdateOne) SetDelkey(s string) *AppointmentUpdateOne {
	auo.mutation.SetDelkey(s)
	return auo
}

// SetNillableDelkey sets the "delkey" field if the given value is not nil.
func (auo *AppointmentUpdateOne) SetNillableDelkey(s *string) *AppointmentUpdateOne {
	if s != nil {
		auo.SetDelkey(*s)
	}
	return auo
}

// SetStartTime sets the "start_time" field.
func (auo *AppointmentUpdateOne) SetStartTime(t time.Time) *AppointmentUpdateOne {
	auo.mutation.SetStartTime(t)
	return auo
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (auo *AppointmentUpdateOne) SetNillableStartTime(t *time.Time) *AppointmentUpdateOne {
	if t != nil {
		auo.SetStartTime(*t)
	}
	return auo
}

// SetEndTime sets the "end_time" field.
func (auo *AppointmentUpdateOne) SetEndTime(t time.Time) *AppointmentUpdateOne {
	auo.mutation.SetEndTime(t)
	return auo
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (auo *AppointmentUpdateOne) SetNillableEndTime(t *time.Time) *AppointmentUpdateOne {
	if t != nil {
		auo.SetEndTime(*t)
	}
	return auo
}

// SetDescription sets the "description" field.
func (auo *AppointmentUpdateOne) SetDescription(s string) *AppointmentUpdateOne {
	auo.mutation.SetDescription(s)
	return auo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (auo *AppointmentUpdateOne) SetNillableDescription(s *string) *AppointmentUpdateOne {
	if s != nil {
		auo.SetDescription(*s)
	}
	return auo
}

// Mutation returns the AppointmentMutation object of the builder.
func (auo *AppointmentUpdateOne) Mutation() *AppointmentMutation {
	return auo.mutation
}

// Where appends a list predicates to the AppointmentUpdate builder.
func (auo *AppointmentUpdateOne) Where(ps ...predicate.Appointment) *AppointmentUpdateOne {
	auo.mutation.Where(ps...)
	return auo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *AppointmentUpdateOne) Select(field string, fields ...string) *AppointmentUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Appointment entity.
func (auo *AppointmentUpdateOne) Save(ctx context.Context) (*Appointment, error) {
	return withHooks(ctx, auo.sqlSave, auo.mutation, auo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AppointmentUpdateOne) SaveX(ctx context.Context) *Appointment {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *AppointmentUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AppointmentUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (auo *AppointmentUpdateOne) check() error {
	if v, ok := auo.mutation.Name(); ok {
		if err := appointment.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Appointment.name": %w`, err)}
		}
	}
	if v, ok := auo.mutation.Email(); ok {
		if err := appointment.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Appointment.email": %w`, err)}
		}
	}
	if v, ok := auo.mutation.Phone(); ok {
		if err := appointment.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "Appointment.phone": %w`, err)}
		}
	}
	if v, ok := auo.mutation.GetType(); ok {
		if err := appointment.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Appointment.type": %w`, err)}
		}
	}
	if v, ok := auo.mutation.Delkey(); ok {
		if err := appointment.DelkeyValidator(v); err != nil {
			return &ValidationError{Name: "delkey", err: fmt.Errorf(`ent: validator failed for field "Appointment.delkey": %w`, err)}
		}
	}
	return nil
}

func (auo *AppointmentUpdateOne) sqlSave(ctx context.Context) (_node *Appointment, err error) {
	if err := auo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(appointment.Table, appointment.Columns, sqlgraph.NewFieldSpec(appointment.FieldID, field.TypeInt))
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Appointment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, appointment.FieldID)
		for _, f := range fields {
			if !appointment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != appointment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.Name(); ok {
		_spec.SetField(appointment.FieldName, field.TypeString, value)
	}
	if value, ok := auo.mutation.Email(); ok {
		_spec.SetField(appointment.FieldEmail, field.TypeString, value)
	}
	if value, ok := auo.mutation.Phone(); ok {
		_spec.SetField(appointment.FieldPhone, field.TypeString, value)
	}
	if value, ok := auo.mutation.GetType(); ok {
		_spec.SetField(appointment.FieldType, field.TypeEnum, value)
	}
	if value, ok := auo.mutation.Delkey(); ok {
		_spec.SetField(appointment.FieldDelkey, field.TypeString, value)
	}
	if value, ok := auo.mutation.StartTime(); ok {
		_spec.SetField(appointment.FieldStartTime, field.TypeTime, value)
	}
	if value, ok := auo.mutation.EndTime(); ok {
		_spec.SetField(appointment.FieldEndTime, field.TypeTime, value)
	}
	if value, ok := auo.mutation.Description(); ok {
		_spec.SetField(appointment.FieldDescription, field.TypeString, value)
	}
	_node = &Appointment{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{appointment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	auo.mutation.done = true
	return _node, nil
}
