// Code generated by ent, DO NOT EDIT.

package ent

import (
	"TerminSystem/ent/appointment"
	"TerminSystem/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	appointmentFields := schema.Appointment{}.Fields()
	_ = appointmentFields
	// appointmentDescName is the schema descriptor for name field.
	appointmentDescName := appointmentFields[0].Descriptor()
	// appointment.NameValidator is a validator for the "name" field. It is called by the builders before save.
	appointment.NameValidator = appointmentDescName.Validators[0].(func(string) error)
	// appointmentDescEmail is the schema descriptor for email field.
	appointmentDescEmail := appointmentFields[1].Descriptor()
	// appointment.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	appointment.EmailValidator = appointmentDescEmail.Validators[0].(func(string) error)
	// appointmentDescPhone is the schema descriptor for phone field.
	appointmentDescPhone := appointmentFields[2].Descriptor()
	// appointment.PhoneValidator is a validator for the "phone" field. It is called by the builders before save.
	appointment.PhoneValidator = appointmentDescPhone.Validators[0].(func(string) error)
	// appointmentDescDelkey is the schema descriptor for delkey field.
	appointmentDescDelkey := appointmentFields[4].Descriptor()
	// appointment.DelkeyValidator is a validator for the "delkey" field. It is called by the builders before save.
	appointment.DelkeyValidator = appointmentDescDelkey.Validators[0].(func(string) error)
}
